name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - fastqc
  - multiqc
  - samtools
  - fastp
  - picard
  - bedtools
  - bowtie2
  - star
  - awscli
  - pip
