flowchart TB
    subgraph " "
    v4["Channel.fromPath"]
    end
    subgraph "TRIMMING_WF [TRIMMING_WF]"
    v15(["TRIM_READS_FASTP"])
    end
    subgraph "TWOPASS_ALIGNMENT_WF [TWOPASS_ALIGNMENT_WF]"
    v16(["ALIGN_READS_TWOPASS_STARSAM"])
    v17(["FIXMATES_MARKDUPES_SAMTOOLS"])
    end
    subgraph "HLA_TYPING_WF [HLA_TYPING_WF]"
    v18(["TYPE_HLA_ALLELES_ARCASHLA"])
    v19(["REFORMAT_HLA_TYPES_PYENV"])
    v21(["COLLATE_HLA_FILES_BASH"])
    v20(( ))
    end
    subgraph "AGGREGATE_FUSION_CALLING_WF [AGGREGATE_FUSION_CALLING_WF]"
    v22(["ALIGN_READS_STAR_GENERAL"])
    v23(["FILTER_ALIGNED_READS_EASYFUSE"])
    v24(["CONVERT_FILTREADS_BAM2FASTQ_EASYFUSE"])
    v25(["ALIGN_READS_STAR_ARRIBA"])
    v26(["CALL_FUSIONS_ARRIBA"])
    v27(["CALL_FUSIONS_FUSIONCATCHER"])
    v28(["CALL_FUSIONS_STARFUSION"])
    v31(["COLLATE_FUSIONS_PYENV"])
    v32(["FILTER_FUSIONS_PYENV"])
    v29(( ))
    end
    subgraph "IN_SILICO_TRANSCRIPT_VALIDATION_WF [IN_SILICO_TRANSCRIPT_VALIDATION_WF]"
    v33(["TRANSLATE_IN_SILICO_AGFUSION"])
    v37(["VALIDATE_IN_SILICO_FUSIONINSPECTOR"])
    v34(( ))
    end
    subgraph "RECURRENT_FUSION_FILTERING_WF [RECURRENT_FUSION_FILTERING_WF]"
    v39(["CONCAT_NORMFILTERED_FUSION_FILES_PYENV"])
    v40(["GET_COHORT_RECURRENT_FUSIONS_PYENV"])
    end
    subgraph " "
    v41[" "]
    v49[" "]
    v50["recurrentValidatedDir"]
    v51[" "]
    v55[" "]
    v58[" "]
    v59[" "]
    v65[" "]
    end
    subgraph "NEOANTIGEN_PREDICTION_WF [NEOANTIGEN_PREDICTION_WF]"
    v45(["KEEP_VALIDATED_FUSIONS_PYENV"])
    v48(["FILTER_VALIDATED_FUSIONS_FOR_RECURRENT_PYENV"])
    subgraph "NEOANTIGEN_PREDICTION_WF:SAMPLE_SPECIFIC_NEOANTIGENS [SAMPLE_SPECIFIC_NEOANTIGENS]"
    v54(["PREDICT_SAMPLE_SPECIFIC_NEOPEPTIDES_PVACFUSE"])
    end
    subgraph "NEOANTIGEN_PREDICTION_WF:COHORTWIDE_NEOANTIGENS [COHORTWIDE_NEOANTIGENS]"
    v57(["FILTER_HLA_ALLOTYPES_FREQ_PYENV"])
    v64(["PREDICT_COHORTWIDE_NEOPEPTIDES_PVACFUSE"])
    v56(( ))
    v60(( ))
    end
    v42(( ))
    v46(( ))
    end
    v5(( ))
    v38(( ))
    v4 --> v5
    v5 --> v15
    v15 --> v16
    v15 --> v22
    v15 --> v34
    v16 --> v17
    v17 --> v18
    v18 --> v19
    v19 --> v20
    v20 --> v21
    v21 --> v54
    v21 --> v56
    v22 --> v23
    v23 --> v24
    v24 --> v25
    v24 --> v27
    v24 --> v28
    v25 --> v26
    v26 --> v29
    v27 --> v29
    v28 --> v29
    v29 --> v31
    v31 --> v32
    v32 --> v33
    v32 --> v34
    v32 --> v38
    v32 --> v42
    v33 --> v34
    v33 --> v42
    v34 --> v37
    v37 --> v42
    v38 --> v39
    v39 --> v40
    v40 --> v48
    v40 --> v41
    v42 --> v45
    v45 --> v54
    v45 --> v46
    v45 --> v60
    v46 --> v48
    v48 --> v51
    v48 --> v50
    v48 --> v49
    v54 --> v55
    v56 --> v57
    v57 --> v59
    v57 --> v58
    v57 --> v60
    v60 --> v64
    v64 --> v65
