flowchart TB
    subgraph " "
    v4["Channel.fromPath"]
    end
    subgraph "TRIMMING_WF [TRIMMING_WF]"
    v15(["TRIM_READS_FASTP"])
    end
    subgraph "TWOPASS_ALIGNMENT_WF [TWOPASS_ALIGNMENT_WF]"
    v16(["ALIGN_READS_TWOPASS_STARSAM"])
    v17(["FIXMATES_MARKDUPES_SAMTOOLS"])
    end
    subgraph "HLA_TYPING_WF [HLA_TYPING_WF]"
    v18(["TYPE_HLA_ALLELES_ARCASHLA"])
    v19(["REFORMAT_HLA_TYPES_PYENV"])
    v21(["COLLATE_HLA_FILES_BASH"])
    v20(( ))
    end
    subgraph " "
    v22["sampleSpecificHLAsTsv"]
    v42[" "]
    v49["cohortValidatedFusions"]
    v53[" "]
    v54["recurrentValidatedDir"]
    v55[" "]
    end
    subgraph "AGGREGATE_FUSION_CALLING_WF [AGGREGATE_FUSION_CALLING_WF]"
    v23(["ALIGN_READS_STAR_GENERAL"])
    v24(["FILTER_ALIGNED_READS_EASYFUSE"])
    v25(["CONVERT_FILTREADS_BAM2FASTQ_EASYFUSE"])
    v26(["ALIGN_READS_STAR_ARRIBA"])
    v27(["CALL_FUSIONS_ARRIBA"])
    v28(["CALL_FUSIONS_FUSIONCATCHER"])
    v29(["CALL_FUSIONS_STARFUSION"])
    v32(["COLLATE_FUSIONS_PYENV"])
    v33(["FILTER_FUSIONS_PYENV"])
    v30(( ))
    end
    subgraph "IN_SILICO_TRANSCRIPT_VALIDATION_WF [IN_SILICO_TRANSCRIPT_VALIDATION_WF]"
    v34(["TRANSLATE_IN_SILICO_AGFUSION"])
    v38(["VALIDATE_IN_SILICO_FUSIONINSPECTOR"])
    v35(( ))
    end
    subgraph "RECURRENT_FUSION_FILTERING_WF [RECURRENT_FUSION_FILTERING_WF]"
    v40(["CONCAT_NORMFILTERED_FUSION_FILES_PYENV"])
    v41(["GET_COHORT_RECURRENT_FUSIONS_PYENV"])
    end
    subgraph "NEOANTIGEN_PREDICTION_WF [NEOANTIGEN_PREDICTION_WF]"
    v46(["KEEP_VALIDATED_FUSIONS_PYENV"])
    subgraph "NEOANTIGEN_PREDICTION_WF:COLLECT_COHORTWIDE_FI_VALIDATED_FUSIONS [COLLECT_COHORTWIDE_FI_VALIDATED_FUSIONS]"
    v48(["COLLECT_COHORTWIDE_VALIDATED_FUSIONS_PYENV"])
    end
    v52(["FILTER_VALIDATED_FUSIONS_FOR_RECURRENT_PYENV"])
    v43(( ))
    v47(( ))
    v50(( ))
    end
    v5(( ))
    v39(( ))
    v4 --> v5
    v5 --> v15
    v15 --> v16
    v15 --> v23
    v15 --> v35
    v16 --> v17
    v17 --> v18
    v18 --> v19
    v19 --> v20
    v20 --> v21
    v21 --> v22
    v23 --> v24
    v24 --> v25
    v25 --> v26
    v25 --> v28
    v25 --> v29
    v26 --> v27
    v27 --> v30
    v28 --> v30
    v29 --> v30
    v30 --> v32
    v32 --> v33
    v33 --> v34
    v33 --> v35
    v33 --> v39
    v33 --> v43
    v34 --> v35
    v34 --> v43
    v35 --> v38
    v38 --> v43
    v39 --> v40
    v40 --> v41
    v41 --> v52
    v41 --> v42
    v43 --> v46
    v46 --> v47
    v46 --> v50
    v47 --> v48
    v48 --> v49
    v50 --> v52
    v52 --> v55
    v52 --> v54
    v52 --> v53
