flowchart TB
    subgraph " "
    v4["Channel.fromPath"]
    v18["starIndex"]
    v20["arribaDB"]
    v22["fuscatDB"]
    v24["ctatDB"]
    v36["metaDataDir"]
    end
    subgraph "TRIMMING_WF [TRIMMING_WF]"
    v17(["TRIM_READS_FASTP"])
    end
    subgraph "AGGREGATE_FUSION_CALLING_WF [AGGREGATE_FUSION_CALLING_WF]"
    v19(["ALIGN_READS_STAR_ARRIBA"])
    v21(["CALL_FUSIONS_ARRIBA"])
    v23(["CALL_FUSIONS_FUSIONCATCHER"])
    v25(["CALL_FUSIONS_STARFUSION"])
    subgraph "AGGREGATE_FUSION_CALLING_WF:COLLECT_COHORTWIDE_UNFILTERED_FUSIONS [COLLECT_COHORTWIDE_UNFILTERED_FUSIONS]"
    v28(["COLLATE_FUSIONS_PYENV"])
    v30(["WRANGLE_RAW_FUSIONS_PYENV"])
    v32(["COLLECT_COHORTWIDE_UNFILTERED_FUSIONS_PYENV"])
    v31(( ))
    end
    subgraph "AGGREGATE_FUSION_CALLING_WF:COLLATE_FILTER_FUSIONS [COLLATE_FILTER_FUSIONS]"
    v34(["COLLATE_FUSIONS_PYENV"])
    v37(["FILTER_FUSIONS_PYENV"])
    end
    v26(( ))
    end
    subgraph " "
    v29[" "]
    v33[" "]
    v35[" "]
    v38["uniqueFiltFusionPairsForFusInsCh"]
    v39["normFilteredFusionsCh"]
    end
    v5(( ))
    v4 --> v5
    v5 --> v17
    v17 --> v19
    v17 --> v23
    v17 --> v25
    v18 --> v19
    v19 --> v21
    v20 --> v21
    v21 --> v26
    v22 --> v23
    v23 --> v26
    v24 --> v25
    v25 --> v26
    v26 --> v28
    v28 --> v30
    v28 --> v29
    v30 --> v31
    v31 --> v32
    v32 --> v33
    v26 --> v34
    v34 --> v37
    v34 --> v35
    v36 --> v37
    v37 --> v39
    v37 --> v38
