flowchart TB
    subgraph " "
    v4["Channel.fromPath"]
    v16["starIndex"]
    end
    subgraph "TRIMMING_WF [TRIMMING_WF]"
    v15(["TRIM_READS_FASTP"])
    end
    subgraph "TWOPASS_ALIGNMENT_WF [TWOPASS_ALIGNMENT_WF]"
    v17(["ALIGN_READS_TWOPASS_STARSAM"])
    v18(["FIXMATES_MARKDUPES_SAMTOOLS"])
    end
    subgraph "HLA_TYPING_WF [HLA_TYPING_WF]"
    v19(["TYPE_HLA_ALLELES_ARCASHLA"])
    v20(["REFORMAT_HLA_TYPES_PYENV"])
    v22(["COLLATE_HLA_FILES_BASH"])
    v21(( ))
    end
    subgraph " "
    v23["sampleSpecificHLAsTsv"]
    end
    v5(( ))
    v4 --> v5
    v5 --> v15
    v15 --> v17
    v16 --> v17
    v17 --> v18
    v18 --> v19
    v19 --> v20
    v20 --> v21
    v21 --> v22
    v22 --> v23
