flowchart TB
    subgraph " "
    v4["Channel.fromPath"]
    v16["starIndex"]
    v26["starIndex"]
    v28["arribaDB"]
    v30["fuscatDB"]
    v32["ctatDB"]
    v38["metaDataDir"]
    v40["starIndex"]
    v48["ctatDB"]
    v77["metaDataDir"]
    end
    subgraph "TRIMMING_WF [TRIMMING_WF]"
    v15(["TRIM_READS_FASTP"])
    end
    subgraph "GENERAL_READS_ALIGNMENT_WF [GENERAL_READS_ALIGNMENT_WF]"
    v17(["ALIGN_READS_STAR_GENERAL"])
    end
    subgraph "HLA_TYPING_WITH_FALLBACK_WF [HLA_TYPING_WITH_FALLBACK_WF]"
    v18(["TYPE_HLAS_WITH_FALLBACK_ARCASHLA"])
    v22(["REFORMAT_AND_COLLATE_HLA_RESULTS_PYENV"])
    v20(( ))
    end
    subgraph " "
    v19[" "]
    v23["individualResultDir"]
    v37[" "]
    v43["alignedBam2PassCh"]
    v53[" "]
    v60["cohortValidatedFusions"]
    v64[" "]
    v65[" "]
    v71[" "]
    v72[" "]
    v79[" "]
    end
    subgraph "AGGREGATE_FUSION_CALLING_WF [AGGREGATE_FUSION_CALLING_WF]"
    v24(["FILTER_ALIGNED_READS_EASYFUSE"])
    v25(["CONVERT_FILTREADS_BAM2FASTQ_EASYFUSE"])
    v27(["ALIGN_READS_STAR_ARRIBA"])
    v29(["CALL_FUSIONS_ARRIBA"])
    v31(["CALL_FUSIONS_FUSIONCATCHER"])
    v33(["CALL_FUSIONS_STARFUSION"])
    v36(["COLLATE_FUSIONS_PYENV"])
    v39(["FILTER_FUSIONS_PYENV"])
    v34(( ))
    end
    subgraph "TWOPASS_READS_ALIGNMENT_WF [TWOPASS_READS_ALIGNMENT_WF]"
    v41(["ALIGN_READS_TWOPASS_STARSAM"])
    v42(["FIXMATES_MARKDUPES_SAMTOOLS"])
    end
    subgraph "IN_SILICO_TRANSCRIPT_VALIDATION_WF [IN_SILICO_TRANSCRIPT_VALIDATION_WF]"
    v44(["TRANSLATE_IN_SILICO_AGFUSION"])
    v49(["VALIDATE_IN_SILICO_FUSIONINSPECTOR"])
    v45(( ))
    end
    subgraph "RECURRENT_FUSION_FILTERING_WF [RECURRENT_FUSION_FILTERING_WF]"
    v51(["CONCAT_NORMFILTERED_FUSION_FILES_PYENV"])
    v52(["GET_COHORT_RECURRENT_FUSIONS_PYENV"])
    end
    subgraph "NEOANTIGEN_PREDICTION_WF [NEOANTIGEN_PREDICTION_WF]"
    v57(["KEEP_VALIDATED_FUSIONS_PYENV"])
    subgraph "NEOANTIGEN_PREDICTION_WF:COLLECT_COHORTWIDE_FI_VALIDATED_FUSIONS [COLLECT_COHORTWIDE_FI_VALIDATED_FUSIONS]"
    v59(["COLLECT_COHORTWIDE_VALIDATED_FUSIONS_PYENV"])
    end
    v63(["FILTER_VALIDATED_FUSIONS_FOR_RECURRENT_PYENV"])
    subgraph "NEOANTIGEN_PREDICTION_WF:COHORT_LEVEL_HLA_NEOANTIGENS [COHORT_LEVEL_HLA_NEOANTIGENS]"
    v70(["FILTER_HLA_ALLOTYPES_FREQ_PYENV"])
    v78(["PREDICT_NEOPEPTIDES_COHORT_LEVEL_HLAS_PVACFUSE"])
    v69(( ))
    v73(( ))
    end
    v54(( ))
    v58(( ))
    v61(( ))
    v68(( ))
    end
    v5(( ))
    v50(( ))
    v4 --> v5
    v5 --> v15
    v15 --> v17
    v15 --> v41
    v15 --> v45
    v16 --> v17
    v17 --> v18
    v17 --> v24
    v18 --> v19
    v18 --> v20
    v20 --> v22
    v22 --> v23
    v22 --> v69
    v24 --> v25
    v25 --> v27
    v25 --> v31
    v25 --> v33
    v26 --> v27
    v27 --> v29
    v28 --> v29
    v29 --> v34
    v30 --> v31
    v31 --> v34
    v32 --> v33
    v33 --> v34
    v34 --> v36
    v36 --> v39
    v36 --> v37
    v38 --> v39
    v39 --> v44
    v39 --> v45
    v39 --> v50
    v39 --> v54
    v40 --> v41
    v41 --> v42
    v42 --> v43
    v44 --> v45
    v44 --> v54
    v48 --> v49
    v45 --> v49
    v49 --> v54
    v50 --> v51
    v51 --> v52
    v52 --> v63
    v52 --> v53
    v54 --> v57
    v57 --> v58
    v57 --> v61
    v58 --> v59
    v59 --> v60
    v61 --> v63
    v63 --> v65
    v63 --> v64
    v63 --> v68
    v69 --> v70
    v70 --> v72
    v70 --> v71
    v70 --> v73
    v77 --> v78
    v73 --> v78
    v78 --> v79
    v68 --> v73
