flowchart TB
    subgraph " "
    v3["Channel.fromFilePairs"]
    end
    subgraph "TRIMMING_WF [TRIMMING_WF]"
    v7(["TRIM_READS_FASTP"])
    end
    subgraph "TWOPASS_ALIGNMENT_WF [TWOPASS_ALIGNMENT_WF]"
    v8(["ALIGN_READS_TWOPASS_STARSAM"])
    v9(["FIXMATES_MARKDUPES_SAMTOOLS"])
    end
    subgraph "HLA_TYPING_WF [HLA_TYPING_WF]"
    v10(["TYPE_HLA_ALLELES_ARCASHLA"])
    v11(["REFORMAT_HLA_TYPES_PYENV"])
    v13(["COLLATE_HLA_FILES_BASH"])
    v12(( ))
    end
    subgraph " "
    v14[" "]
    end
    subgraph "AGGREGATE_FUSION_CALLING_WF [AGGREGATE_FUSION_CALLING_WF]"
    v15(["ALIGN_READS_STAR_GENERAL"])
    v16(["FILTER_ALIGNED_READS_EASYFUSE"])
    v17(["CONVERT_FILTREADS_BAM2FASTQ_EASYFUSE"])
    v18(["ALIGN_READS_STAR_ARRIBA"])
    v19(["CALL_FUSIONS_ARRIBA"])
    v20(["CALL_FUSIONS_FUSIONCATCHER"])
    v22(["COLLATE_FUSIONS_PYENV"])
    v23(["FILTER_FUSIONS_PYENV"])
    v21(( ))
    end
    subgraph "IN_SILICO_TRANSCRIPT_VALIDATION_WF [IN_SILICO_TRANSCRIPT_VALIDATION_WF]"
    v24(["TRANSLATE_IN_SILICO_AGFUSION"])
    v25(["VALIDATE_IN_SILICO_FUSIONINSPECTOR"])
    end
    v4(( ))
    v3 --> v4
    v4 --> v7
    v7 --> v8
    v7 --> v15
    v8 --> v9
    v9 --> v10
    v10 --> v11
    v11 --> v12
    v12 --> v13
    v13 --> v14
    v15 --> v16
    v16 --> v17
    v17 --> v18
    v17 --> v20
    v18 --> v19
    v19 --> v21
    v20 --> v21
    v21 --> v22
    v22 --> v23
    v23 --> v24
    v23 --> v25
    v24 --> v25
