flowchart TB
    subgraph " "
    v0["Channel.fromPath"]
    end
    subgraph TRIMMING_WF
    v4([TRIM_READS_FASTP])
    v1(( ))
    end
    subgraph TWOPASS_ALIGNMENT_WF
    v5([ALIGN_READS_TWOPASS_STARSAM])
    v6([FIXMATES_MARKDUPES_SAMTOOLS])
    end
    subgraph HLA_TYPING_WF
    v7([TYPE_HLA_ALLELES_ARCASHLA])
    v8([REFORMAT_HLA_TYPES_PYENV])
    v9(( ))
    end
    subgraph HLA_TYPE_COLLATION_WF
    v10([COLLATE_HLA_FILES_BASH])
    end
    subgraph " "
    v11[" "]
    v18[" "]
    end
    subgraph AGGREGATE_FUSION_CALLING_WF
    v12([CALL_FUSIONS_ARRIBA_V1])
    v13([CALL_FUSIONS_FUSIONCATCHER])
    v15([COLLATE_FUSIONS_PYENV])
    v16([FILTER_FUSIONS_PYENV])
    v14(( ))
    end
    subgraph PREDICT_CODING_SEQ_WF
    v17([TRANSLATE_IN_SILICO_AGFUSION])
    end
    v0 --> v1
    v1 --> v4
    v4 --> v5
    v4 --> v12
    v4 --> v13
    v5 --> v6
    v6 --> v7
    v7 --> v8
    v8 --> v9
    v9 --> v10
    v10 --> v11
    v12 --> v14
    v13 --> v14
    v14 --> v15
    v15 --> v16
    v16 --> v17
    v17 --> v18
